// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RolemasterCharacterCreation.Data;

#nullable disable

namespace RolemasterCharacterCreation.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619183559_AddWorldMaps")]
    partial class AddWorldMaps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.AttackTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CritTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisarmMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubdualMod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AttackTables");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.AttackTableRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("At1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("At9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttackTableId")
                        .HasColumnType("int");

                    b.Property<int>("RollHigh")
                        .HasColumnType("int");

                    b.Property<int>("RollLow")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AttackTableId", "Size");

                    b.ToTable("AttackTableRows");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.AttackTableWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackTableId")
                        .HasColumnType("int");

                    b.Property<string>("Fumble")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeMod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttackTableId");

                    b.ToTable("AttackTableWeapons");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("ArmorFullSuit")
                        .HasColumnType("bit");

                    b.Property<int>("ArmorType")
                        .HasColumnType("int");

                    b.Property<string>("Build")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("int");

                    b.Property<string>("EyeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GreavesGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HairColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int");

                    b.Property<string>("HelmetGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("LevelUpBaselineJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalSkillData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceBonusDp")
                        .HasColumnType("int");

                    b.Property<string>("Realm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShieldType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatBaselineJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VambracesGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeightKg")
                        .HasColumnType("int");

                    b.Property<int>("WizardStep")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAuditLogs");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterEquipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Name")
                        .IsUnique();

                    b.ToTable("CharacterEquipmentItems");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterFavoriteAttack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackTableId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackTableId");

                    b.HasIndex("CharacterId", "AttackTableId")
                        .IsUnique();

                    b.ToTable("CharacterFavoriteAttacks");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CulturalRanks")
                        .HasColumnType("int");

                    b.Property<bool>("IsKnack")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfessionalSkill")
                        .HasColumnType("bit");

                    b.Property<int>("PurchasedRanks")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "SkillName", "Specialization")
                        .IsUnique()
                        .HasFilter("[Specialization] IS NOT NULL");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Potential")
                        .HasColumnType("int");

                    b.Property<int>("Special")
                        .HasColumnType("int");

                    b.Property<int>("Stat")
                        .HasColumnType("int");

                    b.Property<int>("Temporary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Stat")
                        .IsUnique();

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterTalent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Restriction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterTalents");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CreatureDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CreatureDescriptions");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CriticalTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CriticalTables");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CriticalTableRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriticalTableId")
                        .HasColumnType("int");

                    b.Property<string>("D")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollHigh")
                        .HasColumnType("int");

                    b.Property<int>("RollLow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriticalTableId");

                    b.ToTable("CriticalTableRows");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.FumbleTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Col1Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col2Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col3Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col4Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col5Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FumbleTables");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.FumbleTableRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Col1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FumbleTableId")
                        .HasColumnType("int");

                    b.Property<int>("RollHigh")
                        .HasColumnType("int");

                    b.Property<int>("RollLow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FumbleTableId");

                    b.ToTable("FumbleTableRows");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.MapCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MapCategories");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.MapCategoryName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MapCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("MapCategoryId");

                    b.ToTable("MapCategoryNames");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaOfEffect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpellListId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpellListId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.SpellFailureTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Col1Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col2Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col3Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col4Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SpellFailureTables");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.SpellFailureTableRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Col1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Col4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RollHigh")
                        .HasColumnType("int");

                    b.Property<int>("RollLow")
                        .HasColumnType("int");

                    b.Property<int>("SpellFailureTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellFailureTableId");

                    b.ToTable("SpellFailureTableRows");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.SpellList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Name");

                    b.ToTable("SpellLists");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.TownLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureIndex")
                        .HasColumnType("int");

                    b.Property<string>("FeatureKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GmNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MapCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MapCategoryId");

                    b.HasIndex("TownId", "FeatureKind", "FeatureIndex")
                        .IsUnique();

                    b.ToTable("TownLocations");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.WorldCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorldCategories");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.WorldLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GmNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HexQ")
                        .HasColumnType("int");

                    b.Property<int>("HexR")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorldCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("WorldMapId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorldCategoryId");

                    b.HasIndex("WorldMapId", "HexQ", "HexR")
                        .IsUnique();

                    b.ToTable("WorldLocations");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.WorldMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorldMaps");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RolemasterCharacterCreation.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.AttackTableRow", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.AttackTable", "AttackTable")
                        .WithMany("Rows")
                        .HasForeignKey("AttackTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttackTable");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.AttackTableWeapon", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.AttackTable", "AttackTable")
                        .WithMany("Weapons")
                        .HasForeignKey("AttackTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttackTable");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.Character", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.ApplicationUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterAuditLog", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.ApplicationUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RolemasterCharacterCreation.Models.Character", "Character")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterEquipmentItem", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.Character", "Character")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterFavoriteAttack", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.AttackTable", "AttackTable")
                        .WithMany()
                        .HasForeignKey("AttackTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RolemasterCharacterCreation.Models.Character", "Character")
                        .WithMany("FavoriteAttacks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttackTable");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterSkill", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterStat", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.Character", "Character")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CharacterTalent", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.Character", "Character")
                        .WithMany("Talents")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CriticalTableRow", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.CriticalTable", "CriticalTable")
                        .WithMany("Rows")
                        .HasForeignKey("CriticalTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriticalTable");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.FumbleTableRow", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.FumbleTable", "FumbleTable")
                        .WithMany("Rows")
                        .HasForeignKey("FumbleTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FumbleTable");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.MapCategoryName", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.MapCategory", "MapCategory")
                        .WithMany("Names")
                        .HasForeignKey("MapCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapCategory");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.Spell", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.SpellList", "SpellList")
                        .WithMany("Spells")
                        .HasForeignKey("SpellListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpellList");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.SpellFailureTableRow", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.SpellFailureTable", "SpellFailureTable")
                        .WithMany("Rows")
                        .HasForeignKey("SpellFailureTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpellFailureTable");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.TownLocation", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.MapCategory", "MapCategory")
                        .WithMany("Locations")
                        .HasForeignKey("MapCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RolemasterCharacterCreation.Models.Town", "Town")
                        .WithMany("Locations")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapCategory");

                    b.Navigation("Town");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.WorldLocation", b =>
                {
                    b.HasOne("RolemasterCharacterCreation.Models.WorldCategory", "WorldCategory")
                        .WithMany("Locations")
                        .HasForeignKey("WorldCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RolemasterCharacterCreation.Models.WorldMap", "WorldMap")
                        .WithMany("Locations")
                        .HasForeignKey("WorldMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldCategory");

                    b.Navigation("WorldMap");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.ApplicationUser", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.AttackTable", b =>
                {
                    b.Navigation("Rows");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.Character", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("EquipmentItems");

                    b.Navigation("FavoriteAttacks");

                    b.Navigation("Skills");

                    b.Navigation("Stats");

                    b.Navigation("Talents");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.CriticalTable", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.FumbleTable", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.MapCategory", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Names");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.SpellFailureTable", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.SpellList", b =>
                {
                    b.Navigation("Spells");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.Town", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.WorldCategory", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("RolemasterCharacterCreation.Models.WorldMap", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
